### ISSUE TITLE
Add issue labels

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/community#50] opened 2020-05-13 15:30 UTC
I propose we add the following issue labels to all projects to help folks find things to work on and Czars to track high priority work. (see https://github.com/dask/community/issues/49#issuecomment-628049693 for intial proposal).

I think we should ensure that every issue has one label from each category.

- Type
  - Needs Triage
  - Needs Info
  - Bug (Something is broken)
  - Feature (Something is missing)
  - Hygiene (Code quality and project level things like adding issue templates)
  - Testing/CI 
- Area
  - Bag
  - Delayed
  - Core
  - Array
  - Daraframe
  - ML
  - Scheduler
  - Deployment
  - Diagnostics/Dashboard
  - Networking
  - IO
- Skill level
  - Good first Dask ssue
  - Good second Dask issue
  - Expert needed
- Priority
  - High
  - Medium
  - Low

Based on suggestions these would be formatted with a colos, e.g `Type:Needs Triage`, `Area:IO`, `Priority:High`, etc.

If anyone has suggestions please commend below and I'll edit this list accordingly.

**Edit 3 Jun: Add suggested tags and note on formatting.**

**Comment by jacobtomlinson** [comment] 2020-05-13 15:32
@mrocklin also suggested adding stale. I've used [stale bot](https://github.com/probot/stale) in other projects, which would be super fun to add to a project this size! But it can also be a bit overzealous.

**Comment by mrocklin** [comment] 2020-05-13 15:37
I don't think that we want a bot that comments on things, just a bot that tags an issue as unhandled.  That way maintainers don't have to sift through issues to find things that should be pushed forward or cleared out.  It serves the same purpose and needs-triage, just one week later.

**Comment by jsignell** [comment] 2020-05-13 16:00
I just mentioned this in the maintenance meeting today, but wanted to leave a note here about github [org level templates](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository)

**Comment by jacobtomlinson** [comment] 2020-05-13 16:07
@jsignell I think [this](https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file) is what you were talking about.

@mrocklin stale bot is configurable. It can add labels, comment or close at various intervals. You can pick and choose what functionality you want. The problem I always find with it is that you find yourself just removing the stale label continuously on low priority things that you just haven't managed to get to yet.

Perhaps a conservative first stab at a stale bot config would just be to add the stale label to issues with the high priority label after 7 days of inactivity, which would prompt the Czars to push it again.

**Comment by jsignell** [comment] 2020-06-02 18:33
Thanks @jacobtomlinson - I forgot that this already has a bunch of proposed content-area labels. I think in addition to the ones defined above are great although I'd propose adding `Delayed`,  `Bag`, and `Futures`

I assume we'd be replacing old ones like:

 - dataframe -> Area:Dataframe
 - array -> Area:Array
 - io -> Area:FileSystems

Is something generic like `core` still a useful label? I would argue that it is because setting it indicates that the triager has thought about what label to apply and decided on one as opposed to the absence of an area tag being ambiguous.

**Comment by martindurant** [comment] 2020-06-02 18:36
> io -> Area:FileSystems

I oppose this one, because we have a lot of issues around formats, particularly parquet

**Comment by jsignell** [comment] 2020-06-02 18:42
So you are pro keeping IO @martindurant?

**Comment by martindurant** [comment] 2020-06-02 18:43
Either one label for each or, yes, just Area:IO

**Comment by jsignell** [comment] 2020-06-02 20:04
Ok that makes sense to me.

**Comment by jrbourbeau** [comment] 2020-06-02 21:42
Sorry for the delayed response. I'd like to propose we also have a "Type:Needs Info" label. It's useful for once an issue has been triaged, but more info is still required from the issue author (e.g. providing a minimal example)

**Comment by jakirkham** [comment] 2020-06-03 00:47
How should PRs that are not ready for review be handled? Periodically we have PRs that are not ready for review (and we don't want to bother others with), is there a way we can indicate that?

**Comment by dhirschfeld** [comment] 2020-06-03 01:27
> is there a way we can indicate that?

Use a [Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/)?

**Comment by jakirkham** [comment] 2020-06-03 02:47
We do that now. If we want to agree those are things that won't get triaged/labeled, that would be fine.

**Comment by jacobtomlinson** [comment] 2020-06-03 08:58
I think if a PR is in draft we should just ignore it until the author puts it out of draft or specifically requests a review.

**Comment by jacobtomlinson** [comment] 2020-06-03 09:01
I've updated my original post with the suggestions. I'll give this another 24 hours and then aplpy fo dask/dask and dask/distributed unless there are further suggestions.

**Comment by jsignell** [comment] 2020-06-03 14:05
@jacobtomlinson I think Area:Bag and Area:Delayed would also be useful (and currently exist)

**Comment by jsignell** [comment] 2022-01-31 15:59
This is an old issue, but I've been finding myself wanting a regression label and a feature request label. @jacobtomlinson how do you feel about merging https://github.com/dask/.github/pull/7?

**Comment by jacobtomlinson** [comment] 2022-01-31 16:12
Nervous given the age, it may be a little stale. But perhaps we should just go for it and watch for fallout?

**Comment by jsignell** [comment] 2022-01-31 16:15
Yeah I just looked it over and it seems better than where we are currently at.

**Comment by jsignell** [comment] 2022-02-01 18:48
Merged!

**Closed by jsignell** 2022-02-01 18:48 UTC
